,python,ubuntu,23.12.2017 14:45,file:///home/python/.config/libreoffice/4;